---
server:
  port: 9090
spring:
  application:
    name: emlakcepte-gateway
  cloud:
    gateway:
      routes:
        - id: emlakcepte-service
          uri: lb://emlakcepte-service
          predicates:
            - Path=/users/**,/realtyes/**,/products/**
        - id: emlakcepte-banner-service
          uri: http://localhost:8081
          predicates:
            - Path=/banners/**
